apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: python-app-certificate
  namespace: default
spec:
  secretName: example-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: python.example.net
  dnsNames:
    - python.example.net
