apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: python-test-app-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway # This selects Istio's default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "python.example.net" # The external hostname to access your app
    tls:
      httpsRedirect: true # Redirect HTTP to HTTPS
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "python.example.net" # The external hostname to access your app
    tls:
      mode: SIMPLE # Enable TLS termination on this gateway
      credentialName: python-app-certificate # A Kubernetes Secret with the SSL certificate and key (must contain 'tls.crt' and 'tls.key' fields)
