apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: python-test-app-gateway
spec:
  selector:
    app: python-app
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "python.example.net"