apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: python.example.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: python-test-app
            port: 
              number: 80
